<?php
include('header.php');
include_once("../emailconfig.php");
?>
<?php


if(isset($_POST['datasave']))
{
	$ccrmno = $_POST['ccrmno'];
	$raisedate = $_POST['raisedate'];
	$typechange = $_POST['typechange'];
	$location = $_POST['location'];
	$descripchange = $_POST['descripchange'];
	$nature = $_POST['nature'];
	$startdate = $_POST['startdate'];
	$expectdate = $_POST['expectdate'];
	$priority = $_POST['priority'];
	$ismsimpact = $_POST['ismsimpact'];
	$possiblmpact = $_POST['possiblmpact'];
	$approveby = $_POST['approveby'];
	$purpose = $_POST['purpose'];
	$process = $_POST['process'];
	$owner = $_POST['owner'];

	$message = $_POST['message'];
	

	$willchange = $_POST['willchange'];
	$regression = $_POST['regression'];
	$backout = $_POST['backout'];
	$changefails = $_POST['changefails'];
	$conflicting = $_POST['conflicting'];
	$samarth = @$_POST['samarth'];
	$pinaki = @$_POST['pinaki'];
	$rajesh = @$_POST['rajesh'];
	$isms = @$_POST['isms'];


	date_default_timezone_set('Asia/Kolkata');
	$uploadon = date('Y-m-d');
	$daytime = date('Y-m-d h:i:s');
	$utime = date('h:i:s');
	$yr = date('Y');
	$mr = date('m');

	

	$cstl = "INSERT INTO `sc_ccrmdata`(`sc_ccrmno`, `sc_ccrmdate`, `sc_typeofchange`, `sc_location`, `sc_description`, `sc_natureofchange`, `sc_startdate`, `sc_expectedate`, `sc_priority`, `sc_ismsimpact`, `sc_possibleimpact`, `sc_ismsapprove`, `sc_purposeofchange`, `sc_porocessowner`, `sc_owner`, `sc_fulldescription`, `sc_custmbusiness`, `sc_regression`,`sc_backout` ,`sc_potenial`, `sc_conflicting`, `sc_informed_a`, `sc_informed_b`, `sc_informed_c`, `sc_informed_d`, `sc_createdon`, `sc_createdby`, `sc_status`, `sc_action`) VALUES ('$ccrmno','$raisedate','$typechange','$location','$descripchange','$nature','$startdate','$expectdate','$priority','$ismsimpact','$possiblmpact','$approveby','$purpose','$process','$owner','$message','$willchange','$regression','$backout','$changefails','$conflicting','$pinaki','$samarth','$rajesh','$isms','$daytime','$adname','1','0')";
	$csres = mysqli_query($conn,$cstl);

		$mail->addAddress($samarth, 'Samarth Jain');
		$mail->addAddress($pinaki, 'Pinaki Narendra');
		$mail->addAddress($rajesh, 'Rajesh Bisht');
		$mail->addAddress($isms, 'Tanay Dobhal');
		$mail->addCC($ademail,$adname);
		$mail->Subject = 'Change Control Request Form';
    	$mail->Body.= 'Hi, <br>This is email auto generated by ISMS CRM. for reply goto http://isms.silaris.in/ <br><br>';
    	$mail->Body.='<table style="width:100%">';
	
		$mail->Body.='<tr style="background-color:#f5d9af;padding:5px;border:5px solid black;text-align:center;">
		<h2 style="color:#000;font-family:arial;">Change Control Request Form</h2>
		</tr>';

		$mail->Body.='<table border="1" style="width:100%">
			<tr>
				<th>Priority</th>
				<th>CCR Number</th>
				<th>CCR Date & Time</th>
				<th>Type of Change</th>
				
			</tr>
			<tr>
				<td>'.$priority.'</td>
				<td>'.$ccrmno.'</td>
				<td>'.$raisedate.'</td>
				<td>'.$typechange.'</td>
			</tr>
		</table>';

		$mail->Body.='<br>
		
		<table style="width:100%" border="1">
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Location</td>
				<td>'.$location.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Description of Change</td>
				<td>'.$descripchange.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Nature of Change</td>
				<td>'.$nature.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Start Date & Time</td>
				<td>'.$startdate.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Expected Date & Time</td>
				<td>'.$expectdate.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Information Security Impact</td>
				<td>'.$ismsimpact.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Possible Impact Detail</td>
				<td>'.$possiblmpact.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Security Impact Approved By</td>
				<td style="color:#fff">'.$approveby.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Purpose for the changes</td>
				<td>'.$purpose.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Process Owner</td>
				<td>'.$process.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Owner</td>
				<td>'.$owner.'</td>
			</tr>
		</table>
<br>';

$mail->Body.='<table style="width:100%">
	<tr style="padding:2px 0px 2px 2px;">
		<td>'.$message.'</td>
	</tr>
</table>
<br>';
$mail->Body.='<table style="width:100%" border="1">
	<tr style="padding:2px 0px 2px 2px;">
		<td style="font-weight:bold">Will this change cause an outage to customer/business?</td>
		<td>'.$willchange.'</td>
	</tr>
	<tr style="padding:2px 0px 2px 2px;">
		<td style="font-weight:bold">Regression procedure (In case of failure due to changes made)</td>
		<td>'.$regression.'</td>
	</tr>
	<tr style="padding:2px 0px 2px 2px;">
		<td style="font-weight:bold">Required time to back out</td>
		<td>'.$backout.'</td>
	</tr>
	<tr style="padding:2px 0px 2px 2px;">
		<td style="font-weight:bold">Potential Impact if the change fails</td>
		<td>'.$changefails.'</td>
	</tr>
	<tr style="padding:2px 0px 2px 2px;">
		<td style="font-weight:bold">Proposed change conflicting with any other planned change for the same day</td>
		<td>'.$conflicting.'</td>
	</tr>
</table>
<br>
<br>
<br>
<hr>
<table style="width:100%">
		<tr style="text-align:center">
		<h3>Silaris Informations Pvt Ltd</h3>
		
	</tr>
	<tr style="text-align:center">
		<td>14/3, Naraina Industrial Area Phase-II, Naraina New Delhi-110028</td>
	</tr>	
</table>';

	
    	$mail->send();

	if($csres == true )
	{
		header('Location:ccrm.php');
	}
	else
	{
		echo "<script>alert('Message Data Wrong!')</script>";
	}
}
?>
	
	<div class="main-dash">
		<div class="top-dash">
			<nav class="navbar navbar-expand-md bgdark navbar-dark">
			  <!-- Brand -->
			  <a class="navbar-brand" href="#">VERSION : 1.0.1</a>

			  <!-- Toggler/collapsibe Button -->
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
			    <span class="navbar-toggler-icon"></span>
			  </button>

			  <!-- Navbar links -->
			  <div class="collapse navbar-collapse" id="collapsibleNavbar">
			    <ul class="navbar-nav ml-auto">
			      <!-- <li class="nav-item">
			        <a class="nav-link" href="#">Home</a>
			      </li> -->
			      <li class="nav-item">
			        <a class="nav-link" href="isms-policies.php">ISMS Policies</a>
			      </li>
			      <li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="navbardrop"><i class="fa fa-user-circle"></i> <?php echo $adname?></a>
			         <div class="dropdown-menu">
				        <a class="dropdown-item" href="profile.php"> <i class="fa fa-user"></i> Profile</a>
				        <a class="dropdown-item" href="password.php"><i class="fa fa-lock"></i> Password</a>
				        <a class="dropdown-item" href="../logout.php"><i class="fa fa-power-off"></i> Logout</a>
				      </div>
			      </li>
			    </ul>
			  </div>
			  
			</nav>
		</div>
		<div class="side-dash">
			<?php include('sidebar.php');?>
		</div>
		<div class="body-dash">
			<form class="" method="POST" action="">
				<div class="table-responsive">
			<table class="table table-bordered custometh">
				<tr>
					<th>CCRM Number</th>
					<?php
						$cmst = "SELECT * FROM `sc_ccrmdata` WHERE sc_status='1' ORDER BY sc_sno DESC LIMIT 1";
						$cres = mysqli_query($conn,$cmst);
						$crow = mysqli_fetch_array($cres);

						date_default_timezone_set('Asia/Kolkata');
						$uploadon = date('Y-m-d');
						$daytime = date('Y-m-d h:i:s');
						$utime = date('h:i:s');
						$yr = date('Y');
						$mr = date('m');
						$cnum = $crow['sc_sno'];
						$tel = "CCR".$yr.$mr.$cnum;
						
						if(mysqli_num_rows($cres) >= 0)
						{
							?>
							<td><?php echo $tel;?><input type="hidden" name="ccrmno" value="<?php echo $tel;?>"></td>
							<?php
						}
						else
						{
							?>
							<td><?php echo $tel;?><input type="hidden" name="ccrmno" value="<?php echo $tel;?>"></td>
							<?php
						}
					?>
					
					<th>CCRM Raised Date</th>
					<td><input type="datetime-local" name="raisedate" required class="inputap"></td>
					<th>Type of Change</th>
					<td><select class="inputap" name="typechange">
						<option value="" disabled="" selected="">Select Type</option>
						<option value="Installation">Installation</option>
						<option value="Upgrade">Upgrade</option>
						<option value="Maintenance">Maintenance</option>
						<option value="Replacement">Replacement</option>
						<option value="Movement">Movement</option>
					</select></td>
					
				</tr>
				<tr>
					<th>Location</th>
					<td><input type="text" name="location" required class="inputap"></td>
					<th>Description of change</th>
					<td><input type="text" name="descripchange" required class="inputap"></td>
					<th>Nature of Change</th>
					<td><select class="inputap" name="nature">
						<option value="" disabled="" selected="">Select Nature</option>
						<option value="Normal">Normal</option>
						<option value="Emergency">Emergency</option>
						
					</select>
					</td>
				</tr>
				<tr>
					
					<th>Start Date|Time</th>
					<td><input type="datetime-local" name="startdate" required class="inputap"></td>
					<th>Expected Date|Time</th>
					<td><input type="datetime-local" name="expectdate" required class="inputap"></td>
					<th>Priority</th>
					<td><input type="text" name="priority" required class="inputap"></td>
					
				</tr>
				<tr>
					<th>Information Security Impact</th>
					<td><input type="text" name="ismsimpact" required class="inputap"></td>
					<th>Possible Impact Details</th>
					<td><input type="text" name="possiblmpact" required class="inputap"></td>
					<th>Security Impact Approved By</th>
					<td>
						<select class="inputap" name="approveby">
						<option value="" disabled="" selected="">Approved By</option>
						<option value="samarth.jain@silaris.in">Samarth Jain</option>
						<option value="pinaki.narendra@silaris.in">Pinaki Narendra</option>
						<option value="isms@silaris.in">Tanay Dobhal</option>
						
					</select>

					</td>
					
				</tr>
				<tr>
					<th>Purpose for the Changes</th>
					<td><input type="text" name="purpose" required class="inputap"></td>
					<th>Process Owner</th>
					<td><input type="text" name="process" required class="inputap"></td>
					<th>Owner</th>
					<td><input type="text" name="owner" required class="inputap"></td>
				</tr>
				<tr>
					<td colspan="6"><textarea name="message" class="messat"></textarea></td>
				</tr>
				<tr>
					<th colspan="4">Will this change cause an outage to customer/business?</th>
					<td colspan="2"><input type="text" name="willchange" required class="inputap"></td>
					
				</tr>
				<tr>
					
					<th colspan="4">Regression procedure (In case of failure due to changes made)</th>
					<td colspan="2"><input type="text" name="regression" required class="inputap"></td>
					
				</tr>
				<tr>
					
					<th colspan="4">Required time to back out</th>
					<td colspan="2"><input type="text" name="backout" required class="inputap"></td>
					
					
				</tr>
				<tr>
						
					<th colspan="4">Potential Impact if the change fails</th>
					<td colspan="2"><input type="text" name="changefails" required class="inputap"></td>
					
				</tr>
				<tr>
						
					<th colspan="4">Proposed change conflicting with any other planned change for the same day</th>
					<td colspan="2"><input type="text" name="conflicting" required class="inputap"></td>
					
				</tr>
				<tr>
						
					<th colspan="6">Informed all the team members about the change :</th>
					
				</tr>
				<tr>
					<td><input type="checkbox" name="pinaki" value="pinaki.narendra@silaris.in"> Pinaki Narendra</td>
					<td><input type="checkbox" name="samarth" value="samarth.jain@silaris.in" class=""> Samarth Jain</td>
					
					<td><input type="checkbox" name="rajesh" value="rajesh.bisht@silaris.in"> Rajesh Bisht</td>
					<td><input type="checkbox" name="isms" value="isms@silaris.in"> Tanay Dobhal</td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td colspan="4"></td>
					<td>
						<input type="reset" class="">
					</td>
					<td>
						<input type="submit" name="datasave" class="sbsave">
					</td>
					
					
				</tr>
			</table>
			</div>
			</form>
		</div>
	</div>

<?php
include('footer.php');
?>