<?php
include('header.php');
include_once("../emailconfig.php");
?>
<?php
	
if(isset($_GET['tid']))
{
	$tid = $_GET['tid'];
	$cst = "UPDATE `sc_wifiaccess` SET sc_status='0' WHERE sc_sno='$tid'";
	$rst = mysqli_query($conn,$cst);
	if($rst == true)
	{
		header('Location:wifi-access.php');
	}
}
?>
<?php
if(isset($_POST['wifiaccess']))
{
	$empname = $_POST['empname'];
	$desig = $_POST['desig'];
	$depart = $_POST['depart'];
	$foruser = $_POST['foruser'];
	$intenal = $_POST['intenal'];
	$laptopuser = $_POST['laptopuser'];
	$systemsmac = "Filled by Network";
	$accessdate = $_POST['accessdate'];
	$timehr = $_POST['timehr'];

	$sql = "SELECT * FROM `sc_wifiaccess` ORDER BY sc_sno DESC LIMIT 1";
	$res = mysqli_query($conn,$sql);
	$row = mysqli_fetch_array($res);
	$rat = @$row['sc_sno'];
	$val = @$rat+1;
	$vat = "WIFI".$val;

	date_default_timezone_set('Asia/Kolkata');
	
	$daytime = date('Y-m-d h:i:s');
	

	if(mysqli_num_rows($res) < 0)
	{
		$wifi = "INSERT INTO `sc_wifiaccess`(`sc_wifiaccessid`, `sc_wifiname`, `sc_wifidesinations`, `sc_wifiprocess`, `sc_wifiguest`, `sc_wifiempid`, `sc_wifiassets`, `sc_wifisystem`, `sc_wifidate`, `sc_wifiperiod`, `sc_createdby`,`sc_createremail`, `sc_createdon`, `sc_status`) VALUES ('WIFI0','$empname','$desig','$depart','$foruser','$intenal','$laptopuser','$systemsmac','$accessdate','$timehr','$adname','$ademail','$daytime','1')";
		$wires = mysqli_query($conn,$wifi);

		
		$mail->addAddress('isms@silaris.in', 'Tanay Dobhal');
		$mail->addCC($ademail,$adname);
		$mail->Subject = 'Wifi Access Request';
    	$mail->Body.= 'Hi, <br>This is email auto generated by ISMS CRM. for reply goto http://isms.silaris.in/ <br><br>';
    	$mail->Body.='<table style="width:100%">';
	
		$mail->Body.='<tr style="background-color:#f5d9af;padding:5px;border:5px solid black;text-align:center;">
		<h2 style="color:#000;font-family:arial;">Wifi Access Request Form</h2>
		</tr>';

		

		$mail->Body.='
		
		<table style="width:100%" border="1">
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Name</td>
				<td>'.$empname.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Designation</td>
				<td>'.$desig.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Process / Dept</td>
				<td>'.$depart.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Guest/ Client/Internal employee</td>
				<td>'.$foruser.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Employee ID (if internal employee)</td>
				<td>'.$intenal.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Desktop/Laptop user</td>
				<td>'.$laptopuser.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">System MAC Address</td>
				<td>'.$systemsmac.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Date</td>
				<td style="color:#000">'.$accessdate.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Time Period of Internet Access</td>
				<td>'.$timehr.'</td>
			</tr>
			
		</table>
<br>';


$mail->Body.='
<br>
<hr>
<table style="width:100%">
		<tr style="text-align:center">
		<h3>Silaris Informations Pvt Ltd</h3>
		
	</tr>
	<tr style="text-align:center">
		<td>14/3, Naraina Industrial Area Phase-II, Naraina New Delhi-110028</td>
	</tr>	
</table>';

	

		if($wires == true AND $mail->send())
		{
			header('Location:wifi-access.php');
		}
	}
	else
	{
		$wifi = "INSERT INTO `sc_wifiaccess`(`sc_wifiaccessid`, `sc_wifiname`, `sc_wifidesinations`, `sc_wifiprocess`, `sc_wifiguest`, `sc_wifiempid`, `sc_wifiassets`, `sc_wifisystem`, `sc_wifidate`, `sc_wifiperiod`, `sc_createdby`, `sc_createremail`,`sc_createdon`, `sc_status`) VALUES ('$vat','$empname','$desig','$depart','$foruser','$intenal','$laptopuser','$systemsmac','$accessdate','$timehr','$adname','$ademail','$daytime','1')";
		$wires = mysqli_query($conn,$wifi);

		$mail->addAddress('isms@silaris.in', 'Tanay Dobhal');
		$mail->addCC($ademail,$adname);
		$mail->Subject = 'Wifi Access Request';
    	$mail->Body.= 'Hi, <br>This is email auto generated by ISMS CRM. for reply goto http://isms.silaris.in/ <br><br>';
    	$mail->Body.='<table style="width:100%">';
	
		$mail->Body.='<tr style="background-color:#f5d9af;padding:5px;border:5px solid black;text-align:center;">
		<h2 style="color:#000;font-family:arial;">Wifi Access Request Form</h2>
		</tr>';

		

		$mail->Body.='
		
		<table style="width:100%" border="1">
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Name</td>
				<td>'.$empname.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Designation</td>
				<td>'.$desig.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Process / Dept</td>
				<td>'.$depart.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Guest/ Client/Internal employee</td>
				<td>'.$foruser.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Employee ID (if internal employee)</td>
				<td>'.$intenal.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Desktop/Laptop user</td>
				<td>'.$laptopuser.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">System MAC Address</td>
				<td>'.$systemsmac.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Date</td>
				<td style="color:#000">'.$accessdate.'</td>
			</tr>
			<tr style="padding:2px 0px 2px 2px;">
				<td style="font-weight:bold">Time Period of Internet Access</td>
				<td>'.$timehr.'</td>
			</tr>
			
		</table>
<br>';


$mail->Body.='
<br>
<hr>
<table style="width:100%">
		<tr style="text-align:center">
		<h3>Silaris Informations Pvt Ltd</h3>
		
	</tr>
	<tr style="text-align:center">
		<td>14/3, Naraina Industrial Area Phase-II, Naraina New Delhi-110028</td>
	</tr>	
</table>';

		if($wires == true AND $mail->send())
		{
			header('Location:wifi-access.php');
		}
	}

}
?>
	
	<div class="main-dash">
		<div class="top-dash">
			<nav class="navbar navbar-expand-md bgdark navbar-dark">
			  <!-- Brand -->
			  <a class="navbar-brand" href="#">VERSION : 1.0.1</a>

			  <!-- Toggler/collapsibe Button -->
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
			    <span class="navbar-toggler-icon"></span>
			  </button>

			  <!-- Navbar links -->
			  <div class="collapse navbar-collapse" id="collapsibleNavbar">
			    <ul class="navbar-nav ml-auto">
			      <!-- <li class="nav-item">
			        <a class="nav-link" href="#">Home</a>
			      </li> -->
			      <li class="nav-item">
			        <a class="nav-link" href="isms-topics.php">ISMS Topics</a>
			      </li>
			      <li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="navbardrop"><i class="fa fa-user-circle"></i> <?php echo $adname?></a>
			         <div class="dropdown-menu">
				        <a class="dropdown-item" href="profile.php"> <i class="fa fa-user"></i> Profile</a>
				        <a class="dropdown-item" href="password.php"><i class="fa fa-lock"></i> Password</a>
				        <a class="dropdown-item" href="../logout.php"><i class="fa fa-power-off"></i> Logout</a>
				      </div>
			      </li>
			    </ul>
			  </div>
			  
			</nav>
		</div>
		<div class="side-dash">
			<?php include('sidebar.php');?>
		</div>
		<div class="body-dash">
			<div class="row mb-4">
				<div class="col-lg-6 col-md-6">
					<a href="wifi-history.php" class="btn btn-warning"><i class="fa fa-history"></i> History</a>
				</div>
				<div class="col-lg-6 col-md-6">
					<div class="clearfix">
					<?php
						if(($ademail == "rajesh.bisht@silaris.in"))
						{
							echo "";
						}
						else
						{
							?>
							<button class="btn btn-info float-right" id="addform"> <i class="fa fa-wifi"> </i> Wifi Access Form</button>
							<?php
						}
						?>
					</div>
				</div>
									
			</div>
			
			<div class="table-wrapper-scroll-y my-custom-scrollbar table-responsive">
				<table class="table table-bordered table-striped table-hover">
					<thead class="bgsky">
						<td>S.No</td>
						<td>Wifi_Access_ID</td>
						<td>Created BY</td>
						<td>Created_On</td>
						<td>Name</td>
						<td>Designation</td>
						<td>Process / Dept.</td>
						<td>User For</td>
						<td>Employee ID <small><em>(Optional)<em></small></td>
						<td>User Assets Type</td>
						<td>MAC Address</td>
						<td>Date</td>
						<td>Time Period</td>
						<td>ISMS Dept.</td>
						
						<td>Network</td>
						<?php
						if(($ademail == "rajesh.bisht@silaris.in"))
						{
							?>
							<td>Action</td>
							
							<?php
						}
							?>
						
					</thead>
					<tbody>
						<?php
						if(($ademail == "rajesh.bisht@silaris.in"))
						{
							
						$num =1;
							$tsql = "SELECT * FROM `sc_wifiaccess` WHERE sc_status='1' AND sc_wifisms='1' AND sc_wifiactive='0' AND sc_wifit='0' AND sc_createremail='$ademail' ORDER BY sc_sno DESC";
							$tres = mysqli_query($conn,$tsql);
							while($trow = mysqli_fetch_array($tres))
							{
								?>
								<tr>
									<td><?php echo $num;?></td>
									<td><?php echo $trow['sc_wifiaccessid'];?></td>
									<td><?php echo $trow['sc_createdby'];?></td>
									<td><?php echo $trow['sc_createdon'];?></td>
									<td><?php echo $trow['sc_wifiname'];?></td>
									<td><?php echo $trow['sc_wifidesinations'];?></td>
									<td><?php echo $trow['sc_wifiprocess'];?></td>
									<td><?php echo $trow['sc_wifiguest'];?></td>
									<td><?php echo $trow['sc_wifiempid'];?></td>
									<td><?php echo $trow['sc_wifiassets'];?></td>
									<td><?php echo $trow['sc_wifisystem'];?></td>
									<td><?php echo $trow['sc_wifidate'];?></td>
									<td><?php echo $trow['sc_wifiperiod'];?></td>
									
									<td><?php
									$hrid = $trow['sc_wifisms']; 
										if($hrid == "0")
										{
											echo "<img src='../assets/img/red.png'>";
										}
										else
										{
											echo "<img src='../assets/img/green.png'>";
										}
									
									
									
									?></td>
									
									<td><?php
									$act = $trow['sc_wifinetwork']; 
										if($act == "0")
										{
											echo "<img src='../assets/img/red.png'>";
										}
										else
										{
											echo "<img src='../assets/img/green.png'>";
										}
									
									?></td>
									
							<td><a href="wifi-approve.php?wid=<?php echo $trow['sc_sno'];?>" class="aprv">Approve</a></td>

							
									
									
								</tr>
								<?php
								$num++;
							}
							}
							else
							{
								$num =1;
							$tsql = "SELECT * FROM `sc_wifiaccess` WHERE sc_status='1' AND sc_wifiactive='0' AND sc_wifit='0' AND sc_createremail='$ademail' ORDER BY sc_sno DESC";
							$tres = mysqli_query($conn,$tsql);
							while($trow = mysqli_fetch_array($tres))
							{
								?>
								<tr>
									<td><?php echo $num;?></td>
									<td><?php echo $trow['sc_wifiaccessid'];?></td>
									<td><?php echo $trow['sc_createdby'];?></td>
									<td><?php echo $trow['sc_createdon'];?></td>
									<td><?php echo $trow['sc_wifiname'];?></td>
									<td><?php echo $trow['sc_wifidesinations'];?></td>
									<td><?php echo $trow['sc_wifiprocess'];?></td>
									<td><?php echo $trow['sc_wifiguest'];?></td>
									<td><?php echo $trow['sc_wifiempid'];?></td>
									<td><?php echo $trow['sc_wifiassets'];?></td>
									<td><?php echo $trow['sc_wifisystem'];?></td>
									<td><?php echo $trow['sc_wifidate'];?></td>
									<td><?php echo $trow['sc_wifiperiod'];?></td>
									
									<td><?php
									$hrid = $trow['sc_wifisms']; 
										if($hrid == "0")
										{
											echo "<img src='../assets/img/red.png'>";
										}
										else
										{
											echo "<img src='../assets/img/green.png'>";
										}
									
									
									
									?></td>
									
									<td><?php
									$act = $trow['sc_wifinetwork']; 
										if($act == "0")
										{
											echo "<img src='../assets/img/red.png'>";
										}
										else
										{
											echo "<img src='../assets/img/green.png'>";
										}
									
									?></td>
									
							

							
									
									
								</tr>
								<?php
								$num++;
							}
						}
						?>
						<tr>
							
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
<div class="internal-form" id="internal">
	<div class="infernal-disp">
		<form class="" method="POST" action="" enctype="multipart/form-data">
			
			<div class="form-group row">
				<div class="col-lg-6 col-md-6">
				<label>Name</label>
				<input type="text" name="empname" class="form-control" required>
				</div>
				<div class="col-lg-6 col-md-6">
					<label>Designation</label>
					<input type="text" name="desig" class="form-control" required>
				</div>

				
			</div>
			<div class="form-group row">
				<div class="col-lg-6 col-md-6">
					<label>Process / Dept.</label>
				<input type="text" name="depart" class="form-control" required>
				</div>
				<div class="col-lg-6 col-md-6">
					<label>Choose one :</label>			
				<ul class="timep">

					<li>Guest <input type="radio" name="foruser" required value="Guest"></li>
					<li>Client <input type="radio" name="foruser" required value="Client"></li>
					<li>Internal Employee <input type="radio" name="foruser" required value="Internal-Employee"></li>
					
				</ul>
				
			
				</div>
				
			</div>
			<div class="form-group row">
				<div class="col-lg-6 col-md-6">
					<label>Employee ID (if internal employee)</label>
				<input type="text" name="intenal" class="form-control">
				</div>
				<div class="col-lg-6 col-md-6">
					<label>Desktop/Laptop user :</label>
				<input type="text" name="laptopuser" class="form-control" required>
				</div>

				
			</div>
			<div class="form-group row">
				
				<div class="col-lg-12 col-md-12">
					<label>Date:</label>
				<input type="date" name="accessdate" class="form-control" required>
				</div>

				
			</div>
			<div class="form-group">
				<label>Time Period of Internet Access: </label>
				<ul class="timep">
					<li>4 to 8 hr. <input type="radio" name="timehr" required value="4-to-8"></li>
					<li>3 days. <input type="radio" name="timehr" required value="3-days"></li>
					<li>1 week. <input type="radio" name="timehr" required value="1-week"></li>
					<li>1 month. <input type="radio" name="timehr" required value="1-month"></li>
					<li>3 month. <input type="radio" name="timehr" required value="3-month"></li>
				</ul>
				
			</div>
			
			<div class="form-group">
				<input type="submit" name="wifiaccess" class="btn btn-dark" value="Submit">
				<button id="closeform" class="btn btn-danger ml-2">Close</button>
			</div>
		</form>
	</div>
</div>
<?php
include('footer.php');
?>